In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../test_results/yunet_new.csv', index_col=0)
df.head()

,x1,y1,x2,y2,face_num,landmarks,confidence,model,img_width,img_height,face_width,face_height,area,pct_of_frame,name,width,height,duration
0,717.0,90.0,1165.0,500.0,0.0,"{'left_eye': [149, 66], 'right_eye': [172, 67]...",0.857385,yunet,1920.0,1080.0,448.000000,410.4,183859.200000,0.088667,Frasier.S08E01-E02.And.the.Dish.Ran.Away.with....,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Silo.S01E09.The.Getaway.2160p.ATVP.WEB-DL.DDP5...,NaN,NaN,NaN
2,265.0,82.0,371.0,208.0,0.0,"{'left_eye': [142, 83], 'right_eye': [167, 83]...",0.912535,yunet,640.0,480.0,106.666667,126.4,13482.666667,0.043889,Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...,NaN,NaN,NaN
3,546.0,61.0,649.0,219.0,1.0,"{'left_eye': [267, 75], 'right_eye': [273, 76]...",0.702972,yunet,640.0,480.0,102.400000,158.4,16220.160000,0.052800,Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...,NaN,NaN,NaN
4,198.0,166.0,260.0,226.0,2.0,"{'left_eye': [100, 119], 'right_eye': [108, 11...",0.549671,yunet,640.0,480.0,61.866667,59.2,3662.506667,0.011922,Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...,NaN,NaN,NaN

In [3]:
faces = pd.read_csv('../data/faces.csv', index_col=0)
faces.head()

,name,img_height,img_width,x1,y1,x2,y2,width,height,area,pct_of_frame,face_num
0,Billions.S01E02.1080p.BluRay.x265-RARBG_40128.png,1080.0,1920.0,323.0,5.0,919.0,731.0,596.0,726.0,432696.0,0.208669,0.0
1,Billions.S01E09.1080p.BluRay.x265-RARBG_52704.png,1080.0,1920.0,262.0,42.0,614.0,507.0,352.0,465.0,163680.0,0.078935,0.0
2,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080.0,1920.0,484.0,389.0,671.0,617.0,187.0,228.0,42636.0,0.020561,0.0
3,Billions.S01E10.1080p.BluRay.x265-RARBG_51504.png,1080.0,1920.0,1003.0,42.0,1195.0,261.0,192.0,219.0,42048.0,0.020278,1.0
4,Billions.S01E12.1080p.BluRay.x265-RARBG_78336.png,1080.0,1920.0,1121.0,66.0,1662.0,824.0,541.0,758.0,410078.0,0.197761,0.0

In [19]:
temp = df.merge(faces[['name', 'face_num']],
                how='left',
                on=['name', 'face_num'])
temp.head()

,x1,y1,x2,y2,face_num,landmarks,confidence,model,img_width,img_height,face_width,face_height,area,pct_of_frame,name,width,height,duration
0,717.0,90.0,1165.0,500.0,0.0,"{'left_eye': [149, 66], 'right_eye': [172, 67]...",0.857385,yunet,1920.0,1080.0,448.000000,410.4,183859.200000,0.088667,Frasier.S08E01-E02.And.the.Dish.Ran.Away.with....,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Silo.S01E09.The.Getaway.2160p.ATVP.WEB-DL.DDP5...,NaN,NaN,NaN
2,265.0,82.0,371.0,208.0,0.0,"{'left_eye': [142, 83], 'right_eye': [167, 83]...",0.912535,yunet,640.0,480.0,106.666667,126.4,13482.666667,0.043889,Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...,NaN,NaN,NaN
3,546.0,61.0,649.0,219.0,1.0,"{'left_eye': [267, 75], 'right_eye': [273, 76]...",0.702972,yunet,640.0,480.0,102.400000,158.4,16220.160000,0.052800,Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...,NaN,NaN,NaN
4,198.0,166.0,260.0,226.0,2.0,"{'left_eye': [100, 119], 'right_eye': [108, 11...",0.549671,yunet,640.0,480.0,61.866667,59.2,3662.506667,0.011922,Will.&.Grace.S03E24.Sons.and.Lovers.Part.I.480...,NaN,NaN,NaN

In [9]:
tp = temp[(temp['x1_x'].notna()) &
          (temp['x1_y'].notna())]
tn = temp[(temp['x1_x'].isna()) &
          (temp['x1_y'].isna())]

In [15]:
faces_positive = faces[faces['x1'].notna()]
eph = df.merge(faces_positive,
               how='left',
               on=['name', 'face_num'])
eph.head()

,x1_x,y1_x,x2_x,y2_x,face_num,landmarks,confidence,model,img_width_x,img_height_x,...,img_height_y,img_width_y,x1_y,y1_y,x2_y,y2_y,width_y,height_y,area_y,pct_of_frame_y
0,717.0,90.0,1165.0,500.0,0.0,"{'left_eye': [149, 66], 'right_eye': [172, 67]...",0.857385,yunet,1920.0,1080.0,...,1080.0,1920.0,650.0,30.0,1128.0,524.0,478.0,494.0,236132.0,0.113875
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,265.0,82.0,371.0,208.0,0.0,"{'left_eye': [142, 83], 'right_eye': [167, 83]...",0.912535,yunet,640.0,480.0,...,480.0,640.0,244.0,71.0,372.0,227.0,128.0,156.0,19968.0,0.065000
3,546.0,61.0,649.0,219.0,1.0,"{'left_eye': [267, 75], 'right_eye': [273, 76]...",0.702972,yunet,640.0,480.0,...,480.0,640.0,550.0,73.0,638.0,231.0,88.0,158.0,13904.0,0.045260
4,198.0,166.0,260.0,226.0,2.0,"{'left_eye': [100, 119], 'right_eye': [108, 11...",0.549671,yunet,640.0,480.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
fp = eph[(eph['x1_x'].notna()) &
         (eph['x1_y'].isna())]

In [ ]:
trans =

In [18]:
print(tp.shape[0])
print(tn.shape[0])
print(fp.shape[0])
print(fn.shape[0])

1474
89
103
0