In [1]:
from pathlib import Path 

import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm
from deepface import DeepFace
from deepface.modules import preprocessing
from deepface.models.facial_recognition.Facenet import load_facenet128d_model

2025-01-29 12:11:53.753096: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
model = load_facenet128d_model()

2025-01-29 12:12:17.481959: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.616604: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.617276: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.621204: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.621824: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.622388: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.718576: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.718723: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.718803: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2025-01-29 12:12:17.718844: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-01-29 12:12:17.719701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9878 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1

In [19]:
images = [cv2.imread(x) for x in Path('../../data/headshots').iterdir()]
resized = np.array([cv2.resize(x, (160, 160)) for x in images])
resized.shape

(38, 160, 160, 3)

In [20]:
model(resized)

<tf.Tensor: shape=(38, 128), dtype=float32, numpy=
array([[-0.32517663,  1.0757916 , -0.37425518, ..., -0.6548573 ,
         2.527985  , -1.9620142 ],
       [ 0.03023246,  1.0040202 ,  0.1057911 , ...,  0.66393787,
         1.0820918 , -2.9749696 ],
       [ 0.22240773,  0.6035547 ,  0.3227654 , ...,  0.08757307,
         0.91477036, -1.7672428 ],
       ...,
       [ 0.41169906,  0.9684578 ,  0.3618447 , ...,  0.42208293,
         1.4888502 , -2.6754816 ],
       [-0.08037604,  1.1508945 , -0.3777412 , ..., -0.4547631 ,
         0.74215126, -1.7814486 ],
       [ 0.26917025,  1.1832147 , -0.10177714, ..., -0.6601373 ,
         1.8990827 , -1.7839286 ]], dtype=float32)>

In [3]:
label_df = pd.read_csv('../../data/test_labeled.csv', index_col=0)
label_df = label_df[label_df['label'].notna()]
label_df = label_df.reset_index(drop=True) 
label_df.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,mouth_left_y,confidence,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet
0,0.299,0.066,0.659,0.893,0.401,0.333,0.572,0.356,0.485,0.503,...,0.689,1.000,0,4224,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-9.00431126e-02,1.53707832e-01,2.39705741e-02...",Hugh Laurie,"[1.7062506675720215, -1.7491936683654785, -0.3..."
1,0.391,0.129,0.748,0.957,0.571,0.410,0.714,0.471,0.680,0.595,...,0.778,1.000,0,5304,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.11312114,0.1268733,0.00903357,-0.03153913,...",Robert Sean Leonard,"[-0.021657362580299377, -1.5123425722122192, -..."
2,0.181,0.220,0.292,0.486,0.215,0.343,0.265,0.320,0.251,0.386,...,0.409,1.000,0,5496,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.02710779,0.19948913,0.03290576,-0.13188788...",Robert Sean Leonard,"[-0.28194111585617065, -1.3996846675872803, -0..."
3,0.529,0.152,0.656,0.454,0.546,0.283,0.595,0.273,0.561,0.341,...,0.383,0.998,1,5496,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-5.59481643e-02,7.91650563e-02,2.86144577e-02...",Hugh Laurie,"[0.12560777366161346, -2.5007336139678955, 0.0..."
4,0.647,0.199,0.757,0.491,0.682,0.315,0.734,0.301,0.718,0.365,...,0.412,0.999,0,5664,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-4.07901593e-02,1.11157432e-01,7.99753368e-02...",Hugh Laurie,"[0.4325483739376068, -1.5880738496780396, -0.0..."

In [50]:
df = pd.read_csv('../../data/yunet_facenet_test_predicted.csv', index_col=0)
# df2 = df2[df2['filepath'].isin(df['filepath'])]
# df2 = df2.rename({'encoding': 'encoding_facenet_custom'}, axis=1)
df.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath,predicted_name,predicted_tmdb_id
1,6,202,186,436,0,0.781,yunet,8,79,19,...,1080,179.2,234.0,41933,0.020,192,"[0.04235725477337837, -0.42495790123939514, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0
0,365,274,678,608,1,0.723,yunet,91,114,103,...,1080,313.6,334.8,104993,0.051,192,"[0.5490447282791138, -0.17489133775234222, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN
15,717,209,1075,601,0,0.848,yunet,144,102,158,...,1080,358.4,392.4,140636,0.068,216,"[-0.056983813643455505, 0.07135702669620514, -...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
14,333,191,544,389,1,0.845,yunet,69,74,79,...,1080,211.2,198.0,41818,0.020,216,"[-0.16046729683876038, -0.4248913824558258, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0
13,70,137,230,295,2,0.804,yunet,22,56,29,...,1080,160.0,158.4,25344,0.012,216,"[-0.21441158652305603, -0.8600454330444336, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0

In [51]:
df = df.merge(label_df[['frame_num', 'face_num', 'label']],
              on=['frame_num', 'face_num'],
              how='inner')
df.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath,predicted_name,predicted_tmdb_id,label
0,570,205,1318,742,0,0.707,yunet,138,117,167,...,748.8,536.4,401656,0.194,4224,"[-1.0689324140548706, -1.1693716049194336, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0,Hugh Laurie
1,672,126,1472,979,0,0.868,yunet,169,126,207,...,800.0,853.2,682560,0.329,5304,"[-2.013545036315918, 0.08056195080280304, -1.3...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN,Robert Sean Leonard
2,973,173,1293,472,0,0.891,yunet,159,83,179,...,320.0,298.8,95616,0.046,5496,"[-0.8957747220993042, -1.2503917217254639, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0,Robert Sean Leonard
3,301,245,595,515,1,0.867,yunet,62,100,78,...,294.4,270.0,79488,0.038,5496,"[-0.5071961879730225, -0.27054619789123535, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN,Hugh Laurie
4,1203,234,1472,490,0,0.885,yunet,208,93,221,...,268.8,255.6,68705,0.033,5664,"[-0.5762256383895874, -0.6041601896286011, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0,Hugh Laurie

In [52]:
correct = df[df['label'] == df['predicted_name']]
correct.shape[0]/df.shape[0]

0.24846625766871167

I'm checking whether the low accuracy has to do with the detection or the encoding by comparing the same encoding against the RetinaFace detections.

In [60]:
yunet_labeled = pd.read_csv('../../data/yunet_facenet_test_labeled.csv', index_col=0)
yunet_labeled = yunet_labeled.reset_index(drop=True)
yunet_labeled.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,left_mouth_y,img_width,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath
0,6,202,186,436,0,0.781,yunet,8,79,19,...,105,1920,1080,179.2,234.0,41933,0.020,192,"[0.04235725477337837, -0.42495790123939514, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
1,365,274,678,608,1,0.723,yunet,91,114,103,...,148,1920,1080,313.6,334.8,104993,0.051,192,"[0.5490447282791138, -0.17489133775234222, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
2,717,209,1075,601,0,0.848,yunet,144,102,158,...,140,1920,1080,358.4,392.4,140636,0.068,216,"[-0.056983813643455505, 0.07135702669620514, -...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
3,333,191,544,389,1,0.845,yunet,69,74,79,...,95,1920,1080,211.2,198.0,41818,0.020,216,"[-0.16046729683876038, -0.4248913824558258, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
4,70,137,230,295,2,0.804,yunet,22,56,29,...,72,1920,1080,160.0,158.4,25344,0.012,216,"[-0.21441158652305603, -0.8600454330444336, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...

In [6]:
retina_labled = label_df.copy()
cap = cv2.VideoCapture(label_df.at[0, 'filepath'])
for idx, row in tqdm(label_df.iterrows(), total=label_df.shape[0]):
    cap.set(cv2.CAP_PROP_POS_FRAMES, row['frame_num'])
    ret, frame = cap.read()
    x1 = int(row['x1'] * row['img_width'])
    y1 = int(row['y1'] * row['img_height'])
    x2 = int(row['x2'] * row['img_width'])
    y2 = int(row['y2'] * row['img_height'])
    face = frame[y1:y2, x1:x2]
    f = preprocessing.normalize_input(preprocessing.resize_image(face, (160, 160)), normalization='Facenet')
    encoding = model(f)[0]._numpy().tolist()
    retina_labled.at[idx, 'encoding'] = encoding

  0%|          | 0/344 [00:00<?, ?it/s]

2025-01-29 12:13:42.503387: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8902
100%|██████████| 344/344 [02:11<00:00,  2.62it/s]

In [7]:
retina_labled.to_csv('../../data/retina_facnet_custom_labeled.csv')

In [72]:
retina_labled.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,mouth_left_y,confidence,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet
0,0.299,0.066,0.659,0.893,0.401,0.333,0.572,0.356,0.485,0.503,...,0.689,1.000,0,4224,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.9253748655319214, -1.6088452339172363, -1....",Hugh Laurie,"[1.7062506675720215, -1.7491936683654785, -0.3..."
1,0.391,0.129,0.748,0.957,0.571,0.410,0.714,0.471,0.680,0.595,...,0.778,1.000,0,5304,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.9976695775985718, 0.26364538073539734, -0....",Robert Sean Leonard,"[-0.021657362580299377, -1.5123425722122192, -..."
2,0.181,0.220,0.292,0.486,0.215,0.343,0.265,0.320,0.251,0.386,...,0.409,1.000,0,5496,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.24852320551872253, -0.20768316090106964, 0...",Robert Sean Leonard,"[-0.28194111585617065, -1.3996846675872803, -0..."
3,0.529,0.152,0.656,0.454,0.546,0.283,0.595,0.273,0.561,0.341,...,0.383,0.998,1,5496,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.3377447128295898, -1.3077608346939087, 0.0...",Hugh Laurie,"[0.12560777366161346, -2.5007336139678955, 0.0..."
4,0.647,0.199,0.757,0.491,0.682,0.315,0.734,0.301,0.718,0.365,...,0.412,0.999,0,5664,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-0.63287353515625, -0.49372053146362305, -0.6...",Hugh Laurie,"[0.4325483739376068, -1.5880738496780396, -0.0..."

In [8]:
retina_predicted = pd.read_csv('/home/amos/programs/CineFace/data/retina_facnet_custom_predicted.csv', index_col=0)
retina_predicted.head()

,x1,y1,x2,y2,right_eye_x,right_eye_y,left_eye_x,left_eye_y,nose_x,nose_y,...,face_num,frame_num,img_width,img_height,filepath,encoding,label,encoding_facenet,predicted_name,predicted_tmdb_id
0,0.299,0.066,0.659,0.893,0.401,0.333,0.572,0.356,0.485,0.503,...,0,4224,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-2.1931021213531494, -1.17027747631073, -0.05...",Hugh Laurie,"[1.7062506675720215, -1.7491936683654785, -0.3...",NaN,NaN
1,0.391,0.129,0.748,0.957,0.571,0.410,0.714,0.471,0.680,0.595,...,0,5304,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.0988036394119263, -1.0765366554260254, -0....",Robert Sean Leonard,"[-0.021657362580299377, -1.5123425722122192, -...",NaN,NaN
2,0.181,0.220,0.292,0.486,0.215,0.343,0.265,0.320,0.251,0.386,...,0,5496,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.62577486038208, -1.069330096244812, -0.908...",Robert Sean Leonard,"[-0.28194111585617065, -1.3996846675872803, -0...",Robert Sean Leonard,2692.0
3,0.529,0.152,0.656,0.454,0.546,0.283,0.595,0.273,0.561,0.341,...,1,5496,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.382394790649414, -1.3583478927612305, -1.6...",Hugh Laurie,"[0.12560777366161346, -2.5007336139678955, 0.0...",Hugh Laurie,41419.0
4,0.647,0.199,0.757,0.491,0.682,0.315,0.734,0.301,0.718,0.365,...,0,5664,1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,"[-1.1185798645019531, -2.8957130908966064, -0....",Hugh Laurie,"[0.4325483739376068, -1.5880738496780396, -0.0...",Hugh Laurie,41419.0

In [9]:
correct = retina_predicted[retina_predicted['label'] == retina_predicted['predicted_name']]
correct.shape[0]/retina_predicted.shape[0]

0.686046511627907

In [11]:
retina_test = pd.read_csv('../../data/retina_facenet_test.csv', index_col=0)
retina_test.head()

,frame_num,face_num,x1,y1,x2,y2,confidence,encoding,img_width,img_height,filepath
0,192,0,434,244,704,626,1.00,"[-0.3028995394706726, -0.7369624376296997, 1.6...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...
1,192,1,8,207,145,424,0.99,"[0.0383196659386158, -0.04507407173514366, -0....",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...
2,216,0,759,221,1031,606,1.00,"[0.27549728751182556, 0.5236592292785645, 0.33...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...
3,216,1,357,176,526,408,1.00,"[-0.515578031539917, -0.3058892786502838, 0.78...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...
4,216,2,82,128,202,314,1.00,"[-0.042339615523815155, -0.806411862373352, -0...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...

In [12]:
retina_facenet_labeled = retina_test.merge(label_df[['frame_num', 'face_num', 'label']],
                                           on=['frame_num', 'face_num'],
                                           how='inner')
retina_facenet_labeled.head()

,frame_num,face_num,x1,y1,x2,y2,confidence,encoding,img_width,img_height,filepath,label
0,4224,0,585,34,1359,972,1.0,"[-2.389906644821167, -0.9608480930328369, -0.6...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie
1,5304,0,748,138,1404,987,1.0,"[-1.2810478210449219, -0.3460087478160858, -0....",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard
2,5496,0,1015,161,1258,491,1.0,"[-1.531701922416687, -1.3877476453781128, -1.8...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard
3,5496,1,344,234,557,524,1.0,"[-1.0702464580535889, -0.505211353302002, -0.4...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie
4,5664,0,343,323,578,636,1.0,"[-1.4132895469665527, -0.9698241949081421, -0....",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie

In [13]:
retina_facenet_labeled.to_csv('../../data/retina_facenet_test_labeled.csv')

In [14]:
retina_facenet_predicted = pd.read_csv('../../data/retina_facenet_test_predicted.csv', index_col=0)
retina_facenet_predicted.head()

,frame_num,face_num,x1,y1,x2,y2,confidence,encoding,img_width,img_height,filepath,label,predicted_name,predicted_tmdb_id
0,4224,0,585,34,1359,972,1.0,"[-2.389906644821167, -0.9608480930328369, -0.6...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie,NaN,NaN
1,5304,0,748,138,1404,987,1.0,"[-1.2810478210449219, -0.3460087478160858, -0....",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,Robert Sean Leonard,2692.0
2,5496,0,1015,161,1258,491,1.0,"[-1.531701922416687, -1.3877476453781128, -1.8...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,Hugh Laurie,41419.0
3,5496,1,344,234,557,524,1.0,"[-1.0702464580535889, -0.505211353302002, -0.4...",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie,Robert Sean Leonard,2692.0
4,5664,0,343,323,578,636,1.0,"[-1.4132895469665527, -0.9698241949081421, -0....",1920,1080,/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie,Robert Sean Leonard,2692.0

In [15]:
correct = retina_facenet_predicted[retina_facenet_predicted['label'] == retina_facenet_predicted['predicted_name']]
correct.shape[0]/retina_facenet_predicted.shape[0]

0.6268221574344023

In [19]:
yunet_facenet_labeled = pd.read_csv('../../data/yunet_facenet_custom_labeled.csv', index_col=0)
yunet_facenet_labeled = yunet_facenet_labeled[yunet_facenet_labeled['label'].notna()]
yunet_facenet_labeled = yunet_facenet_labeled.reset_index(drop=True)
yunet_facenet_labeled.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,img_width,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath,label
0,1088,256,1510,702,0,0.875,yunet,178,120,203,...,1920,1080,422.4,446.4,188559,0.091,5040,"[0.10577846318483353, -1.0977141857147217, -1....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard
1,954,241,1370,691,0,0.889,yunet,165,108,192,...,1920,1080,416.0,450.0,187200,0.090,5088,"[0.13776034116744995, -0.0923459604382515, -1....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard
2,467,176,1037,752,0,0.813,yunet,120,117,144,...,1920,1080,569.6,576.0,328090,0.158,5208,"[-1.0230798721313477, -0.8788691759109497, -1....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie
3,397,108,992,770,0,0.827,yunet,108,112,134,...,1920,1080,595.2,662.4,394260,0.190,5232,"[-1.203155517578125, -1.401168704032898, -1.07...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie
4,1158,166,1459,479,0,0.850,yunet,197,82,217,...,1920,1080,300.8,313.2,94211,0.045,5352,"[-0.7890584468841553, -0.6717908382415771, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Hugh Laurie