In [1]:
from pathlib import Path
import pandas as pd

In [2]:
files = [x for x in Path('../../data').iterdir() if x.suffix == '.csv']
files

[PosixPath('../../data/test_labeled.csv'),
 PosixPath('../../data/labels.csv'),
 PosixPath('../../data/yunet_vgg_test.csv'),
 PosixPath('../../data/sample.csv'),
 PosixPath('../../data/test_predicted.csv'),
 PosixPath('../../data/find_faces_queue_exp_test.csv'),
 PosixPath('../../data/shining.csv'),
 PosixPath('../../data/shining_bat.csv'),
 PosixPath('../../data/clustered.csv'),
 PosixPath('../../data/retinaface_vgg_test.csv'),
 PosixPath('../../data/yunet_facenet_test.csv'),
 PosixPath('../../data/cluster_faces.csv'),
 PosixPath('../../data/test.csv'),
 PosixPath('../../data/cluster_faces_bk.csv')]

In [4]:
yunet_vgg = pd.read_csv('../../data/yunet_vgg_test.csv', index_col=0)
print(yunet_vgg.shape[0])
yunet_vgg.head()

2466

,x1,y1,x2,y2,face_num,landmarks,confidence,model,img_width,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath
0,6,202,186,436,0,"{'left_eye': [8, 79], 'right_eye': [19, 81], '...",0.781,yunet,1920,1080,179.2,234.0,41933,0.020,192,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
1,365,274,678,608,1,"{'left_eye': [91, 114], 'right_eye': [103, 114...",0.723,yunet,1920,1080,313.6,334.8,104993,0.051,192,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
2,717,209,1075,601,0,"{'left_eye': [144, 102], 'right_eye': [158, 10...",0.848,yunet,1920,1080,358.4,392.4,140636,0.068,216,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
3,333,191,544,389,1,"{'left_eye': [69, 74], 'right_eye': [79, 74], ...",0.845,yunet,1920,1080,211.2,198.0,41818,0.020,216,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
4,70,137,230,295,2,"{'left_eye': [22, 56], 'right_eye': [29, 55], ...",0.804,yunet,1920,1080,160.0,158.4,25344,0.012,216,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...

In [6]:
yunet_vgg.at[0, 'encoding']

'[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0049858108777354445, 0.0, 0.0, 0.0, 0.0, 0.027371698246210774, 0.0, 0.0, 0.03023259465526204, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.030473700255867986, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05382095923427429, 0.0, 0.0, 0.008059333574483598, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05753496461700764, 0.0, 0.08782374245083177, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.13219564438612055, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009159370752732807, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.024496879784102397, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01981374831887771, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.028523733887655837, 0.0, 0.0, 0.12267344006241092, 0.0, 0.0, 0.0105930519873559, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027686424839302733, 0.0, 0.02468329010494314, 0.0, 0.0, 0.06607050605103526, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.19368885777304315, 0.0, 0.0, 0.012814510389365546, 0.023964053025632887, 0.030124467009831415, 0.0, 0.0, 0.0, 0.0360127545033866, 0.0, 0.0, 0.0, 0.0, 0.0, 0.029110697963841713, 0.0, 0.0, 0.01803185451879393, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.11117291829885743, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03829702413313516, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.043941608202781784, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001263590928736146, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0012824907682167947, 0.023330346128775624, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06357027811022563, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.020217379864879297, 0.06543305540881811, 0.023953696230075965, 0.07871570195674439, 0.0035601930946567426, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.025822900591515856, 0.0, 0.0, 0.0, 0.043115905365003544, 0.03411305571610054, 0.0, 0.0, 0.0, 0.0, 0.02031545519404309, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0026823155556699205, 0.0, 0.04250259108109225, 0.0, 0.0, 0.0, 0.0873982633908429, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03356141123756483, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0019877562978365734, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007603117855124685, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0214895348361109, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.000755018645538482, 0.0, 0.0035586294510118344, 0.0, 0.0, 0.09468450379917127, 0.047118230136980174, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0013693470479719957, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09606435594511303, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010804967323409919, 0.0, 0.0, 0.07952210110751066, 0.0, 0.0020743139104063618, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.093036739875912, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010536709069658869, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.013428391634713556, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16752005370900794, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.013160692842909317, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009749215382990672, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016578117398321546, 0.0, 0.0, 0.007895166740697039, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.017512889817462303, 0.0, 0.0, 0.0, 0.0, 0.0025730097403754318, 0.0, 0.0, 0.0, 0.0, 0.011766034454050807, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004664468234650497, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.302308832869268e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.003717712380592718, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010747557228299603, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027105970320353213, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08017362679237898, 0.0, 0.008881963871248313, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027855280354177045, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.048013216262284164, 0.0, 0.0, 0.0, 0.0, 0.06538528065833599, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05582974260190268, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04607408215728882, 0.0, 0.0, 0.0, 0.0, 0.0, 0.011179287113123144, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03231675689580986, 0.0, 0.0, 0.0, 0.056231211295016056, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.029316513964757106, 0.0, 0.0, 0.0, 0.12068968699228491, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.015404546221669204, 0.0, 0.0, 0.04883828914291049, 0.0, 0.0017964518098847163, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012019953683106103, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0024616265663776364, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04095138159044433, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0012263754600383414, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03426297951866211, 0.0, 0.006665923100745052, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007741963411200606, 0.02423060439548187, 0.0, 0.0, 0.04347683781528979, 0.0, 0.0, 0.0, 0.029874886985634362, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05420902483903189, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07053574433680375, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02175492678482078, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08974295191105112, 0.0, 0.0, 0.0, 0.020304637929806087, 0.0, 0.0, 0.0, 0.0, 0.015145816819789715, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.10756116396126622, 0.028928835333678536, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03444588607781988, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03655876236531074, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0019183950156158223, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.12351704268269115, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010814531422884027, 0.0, 0.0, 0.0, 0.017219029805078223, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04254664008499025, 0.0, 0.0, 0.07438909624153858, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06825128571990961, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.021877873422300992, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04943808934601543, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0008547772352111464, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016005501346219305, 0.018647582138556218, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09099136499714579, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05254521800697077, 0.0, 0.013552298206901433, 0.0, 0.0033916698071851615, 0.0858334258271421, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03392430855420583, 0.0, 0.0, 0.0, 0.013095348287480954, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.10008627238451391, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.029010480780361444, 0.0, 0.03730368369764296, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.047101227293470646, 0.0, 0.0, 0.035563613052853785, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010219386903111262, 0.0, 0.0, 0.0, 0.02515083830349544, 0.0, 0.0, 0.0, 0.0, 0.036195010106820726, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04934293281832213, 0.033871779127124794, 0.0, 0.0, 0.0, 0.01968307270710281, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0007798517064563927, 0.0, 0.0, 0.0, 0.0, 0.03207819512217923, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05232197919111125, 0.0, 0.0, 0.03104626531143888, 0.0, 0.0, 0.0, 0.0, 0.0, 0.017939730784817663, 0.0, 0.0027366921071142157, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012873594370622353, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07133581991768327, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.017059977623405942, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00043234859274059065, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005454616365770087, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004514187456369511, 0.0, 0.0, 0.0, 0.022048731300979573, 0.0, 0.0, 0.0, 0.016674412348582215, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012572143374557811, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0066891745192422854, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005908251135678663, 0.0, 0.015228320208117598, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06007120210853857, 0.0, 0.0, 0.0, 0.0, 0.0, 0.039375369786787094, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010957970416525924, 0.0, 0.0, 0.0, 0.08219239948055901, 0.0, 0.0, 0.0, 0.0, 0.0, 0.023068162461846523, 0.0, 0.10214080864014641, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0016053888055077565, 0.0, 0.0, 0.0, 0.02668840472211067, 0.0, 0.0, 0.0, 0.0, 0.0, 0.055922484293847004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.032163887293614135, 0.0, 0.0, 0.04886072761670217, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.029948399985465765, 0.0, 0.0, 0.0047602689685265175, 0.05056434474096776, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.006570215360543837, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01653650572864223, 0.0, 0.0, 0.0, 0.005050095005291433, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.025228713006654795, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.023635386380708046, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007048269594502138, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07727155818375674, 0.0, 0.017500127185544296, 0.0, 0.0, 0.005691518502285042, 0.0, 0.017742890173418943, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.008007647090067736, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06979603664985252, 0.0, 0.0, 0.0, 0.0, 0.08512234219325507, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04180735836906556, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027894937656787473, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0073325227603196624, 0.0, 0.0, 0.0, 0.0, 0.04817693612647246, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03548184461453646, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.042832058671538796, 0.0, 0.0, 0.0, 0.0, 0.050864372333848586, 0.0, 0.0, 0.0, 0.0038017081674114246, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.026929375331898348, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004397080296702765, 0.0, 0.0, 0.0, 0.08386579966010486, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.008095916836182526, 0.0, 0.0, 0.0, 0.009840328185727928, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.021532182935294897, 0.0, 0.0, 0.0, 0.0, 0.021373204248623677, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0010870506865575777, 0.012369999123899238, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012023920163316135, 0.0, 0.05801746979822375, 0.0, 0.0, 0.0, 0.0, 0.04519109221603469, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01600183859535037, 0.0, 0.0, 0.0, 0.07197639034770034, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01733510241011276, 0.0, 0.0, 0.0845889604725327, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03245277964388605, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.10966578481027116, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04680510843472759, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0029206178469498847, 0.0, 0.0, 0.0, 0.0032630648045726554, 0.0, 0.0, 0.08200317835090237, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005592191508256332, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.09833243567605762, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.039867084341604866, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01600652277674418, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00827028297623803, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.023859003170858713, 0.0, 0.0, 0.0, 0.0, 0.00804520978514808, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016259263085986624, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00939030704502942, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.008601142472010692, 0.0, 0.0, 0.04283961215776974, 0.03737327596415275, 0.0, 0.11212267769862162, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005660159760227482, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.003582292591504778, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0063116119500947285, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0014235526110464882, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0034156186782434332, 0.0, 0.0, 0.0, 0.0, 0.011663130203338062, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04305414556574912, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08784750683443841, 0.0, 0.0, 0.02197115057782444, 0.0, 0.059912908875244544, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009654745808572547, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.018559404636167242, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02335003528956863, 0.0, 0.0, 0.0245750934642054, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.011751266458532566, 0.0, 0.0, 0.03935099644460027, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03162111921132837, 0.0, 0.0010523947937638842, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00655753822281073, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.052473990851661996, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01956390731243201, 0.0, 0.0, 0.0, 0.0, 0.002486835726714214, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009715197696787779, 0.0, 0.0, 0.0, 0.005619486276735111, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0039156824151709265, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0035766915974702472, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.037569630608605714, 0.0, 0.0, 0.03624958839454343, 0.0, 0.0, 0.0, 0.05683845399190137, 0.0, 0.006478989315509034, 0.0, 0.0, 0.0318677984328307, 0.013222250155936345, 0.0, 0.08849111305796847, 0.0, 0.005087607453789422, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009344525658963682, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.022130238757048254, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0016518202098608921, 0.0, 0.0, 0.016400144003622392, 0.0008535686924131755, 0.0, 0.0, 0.10980636724820876, 0.0, 0.0, 0.0, 0.002756753992555433, 0.0, 0.0, 0.0, 0.05645812786072432, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05464970086536148, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.056487117888895814, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04228017420932617, 0.0, 0.0, 0.0, 0.0, 0.08321627183934688, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.013455436295204048, 0.0, 0.0, 0.038600870466274924, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1540913110981669, 0.0, 0.0, 0.0, 0.0481143153857771, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07582239275232962, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07674346810311038, 0.0, 0.0, 0.0, 0.0, 0.0, 0.009452481566075517, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.07495215794350359, 0.0, 0.0, 0.0, 0.0, 0.0533020305304942, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.035177956284253235, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004699064131524961, 0.0, 0.0, 0.0, 0.00979536874375563, 0.0, 0.0, 0.03435857701636175, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005033992100570346, 0.0, 0.0, 0.0, 0.0, 0.0, 0.03433760244299926, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007676600856996474, 0.022215726942357784, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18526859849781424, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.036267623167863694, 0.03707431629863419, 0.

In [17]:
yunet_facenet = pd.read_csv('../../data/yunet_facenet_test.csv', index_col=0)
print(yunet_facenet.shape[0])
yunet_facenet.head()

2466

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,left_mouth_y,img_width,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath
1,6,202,186,436,0,0.781,yunet,8,79,19,...,105,1920,1080,179.2,234.0,41933,0.020,192,"[0.04235725477337837, -0.42495790123939514, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
0,365,274,678,608,1,0.723,yunet,91,114,103,...,148,1920,1080,313.6,334.8,104993,0.051,192,"[0.5490447282791138, -0.17489133775234222, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
15,717,209,1075,601,0,0.848,yunet,144,102,158,...,140,1920,1080,358.4,392.4,140636,0.068,216,"[-0.056983813643455505, 0.07135702669620514, -...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
14,333,191,544,389,1,0.845,yunet,69,74,79,...,95,1920,1080,211.2,198.0,41818,0.020,216,"[-0.16046729683876038, -0.4248913824558258, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...
13,70,137,230,295,2,0.804,yunet,22,56,29,...,72,1920,1080,160.0,158.4,25344,0.012,216,"[-0.21441158652305603, -0.8600454330444336, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...

In [18]:
yunet_facenet.at[0, 'encoding']

'[0.5490447282791138, -0.17489133775234222, -0.8742648959159851, -1.0649826526641846, 0.13757199048995972, -0.24988135695457458, 0.38424354791641235, 0.3601502776145935, 0.46810343861579895, -0.9899085760116577, 0.03487652540206909, 0.028960788622498512, -0.7316937446594238, -0.8005388975143433, 0.2297775149345398, -0.5925680994987488, -0.8035918474197388, 0.118064284324646, 0.07975421845912933, -1.082895040512085, 0.03737424314022064, 0.11223611980676651, -0.7420675754547119, 0.48160699009895325, 0.5653843879699707, 0.38544073700904846, -0.23150663077831268, 0.012035004794597626, 0.48260825872421265, -0.5497024655342102, 0.08944589644670486, 0.9011736512184143, -0.3503108024597168, 0.06493929773569107, 0.11243860423564911, -0.13247951865196228, 0.12059400230646133, -0.049574680626392365, 0.6177275776863098, -0.715359091758728, 0.04603296518325806, 1.3982778787612915, 0.3324418067932129, -1.435849666595459, -0.3330310583114624, -0.02430436760187149, 0.04198579862713814, -0.5949978828430176, -0.3222695589065552, 0.48443448543548584, -0.15967147052288055, 0.9762240648269653, 1.0120207071304321, -0.9340335130691528, 0.2526457905769348, 0.9705276489257812, 0.0113897193223238, -0.0024445243179798126, 0.4991611838340759, -0.3999786674976349, 0.2524924576282501, -0.022373244166374207, -0.5242064595222473, 1.0077520608901978, 0.6422326564788818, 1.53785240650177, 1.0197306871414185, 0.30011552572250366, -0.26896512508392334, -0.2770501375198364, 1.1358331441879272, -0.7151069641113281, 0.060623325407505035, -1.388796091079712, 0.5429570078849792, -0.33728882670402527, -1.0543859004974365, 0.8573145270347595, -1.3698647022247314, -0.5664733648300171, -0.26326462626457214, 0.6004228591918945, -0.27345848083496094, -0.47583097219467163, -0.15508779883384705, 0.21744728088378906, -0.3939642906188965, 0.06506915390491486, 0.23438608646392822, 0.39375579357147217, 0.48882102966308594, -0.193183034658432, -1.0183323621749878, 0.08007049560546875, 0.46954110264778137, 0.7974074482917786, -0.9560671448707581, -1.1049036979675293, 0.13389314711093903, 0.8314493298530579, -0.5058019757270813, -0.058567311614751816, 0.7987934947013855, -1.0028318166732788, -0.2211194634437561, 0.27239805459976196, 0.16271603107452393, 0.7090599536895752, 0.11265496909618378, 0.2895068824291229, -0.28682905435562134, 0.31826478242874146, 0.1443803608417511, 0.22072507441043854, 0.5606170296669006, 0.633913516998291, -0.6181387901306152, 0.4339795410633087, 0.11615443974733353, -0.07181628048419952, -0.010733254253864288, -0.30343860387802124, 1.1054288148880005, -0.08619417250156403, 0.5105242133140564, -0.8685872554779053, 0.30570292472839355, -1.0054765939712524]'

In [15]:
shining_bat = pd.read_csv('../../data/shining_bat.csv', index_col=0)
shining_bat.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,left_mouth_y,img_width,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath
3,469,115,708,370,0,0.880,yunet,123,88,146,...,127,1280,720,238.933,254.4,60785,0.066,24,"[-1.4607144594192505, -0.2795068025588989, 0.0...",/home/amos/programs/CineFace/data/videos/shini...
0,503,132,751,410,0,0.835,yunet,131,98,153,...,140,1280,720,247.467,278.4,68895,0.075,48,"[-1.2284197807312012, 0.17295539379119873, -0....",/home/amos/programs/CineFace/data/videos/shini...
36,508,137,742,398,0,0.855,yunet,133,96,151,...,137,1280,720,234.667,261.6,61389,0.067,72,"[-1.3641115427017212, 0.6064889430999756, -0.2...",/home/amos/programs/CineFace/data/videos/shini...
32,508,127,751,389,0,0.873,yunet,134,92,158,...,133,1280,720,243.200,261.6,63621,0.069,96,"[-1.7514203786849976, 0.4765245020389557, -0.2...",/home/amos/programs/CineFace/data/videos/shini...
27,486,142,734,396,0,0.884,yunet,125,99,152,...,137,1280,720,247.467,254.4,62956,0.068,120,"[-1.6699159145355225, 0.2706587016582489, -0.5...",/home/amos/programs/CineFace/data/videos/shini...

In [16]:
shining_bat.at[0, 'encoding']

'[-1.2284197807312012, 0.17295539379119873, -0.12372974306344986, 0.34190794825553894, 0.16311246156692505, -0.5620531439781189, -0.15205955505371094, -0.74335777759552, 0.4657849371433258, -1.6377842426300049, 0.12936994433403015, 0.4328376352787018, -0.00428970530629158, -0.5897021293640137, -0.8888469934463501, -0.9350275993347168, 0.69435715675354, 1.1465290784835815, -0.31543049216270447, -1.0627058744430542, 1.177128791809082, 0.37011685967445374, -0.16303597390651703, -0.9781776666641235, -0.7241396903991699, 0.2004638910293579, 0.6962279081344604, -0.39024817943573, -0.20995770394802094, 0.09917279332876205, -0.626758337020874, 1.9463688135147095, 0.06723757833242416, 1.0104702711105347, 1.854679822921753, -1.6064468622207642, 0.7786482572555542, -0.5241417288780212, 0.6556985378265381, -0.5029751062393188, -0.7698927521705627, 1.0846127271652222, -0.029215186834335327, -0.06890606880187988, -0.45348626375198364, 0.4116020202636719, 1.144905924797058, -1.4706813097000122, 0.7143552303314209, 0.9343211650848389, -0.2631147503852844, 0.1631760150194168, 1.500667929649353, -1.480424404144287, 2.191730499267578, 0.6235881447792053, 0.0947345495223999, -0.45055827498435974, 0.027055084705352783, -1.3946571350097656, -0.4339446723461151, 0.3364790081977844, -0.6809139847755432, -0.15163670480251312, -0.24120858311653137, 1.804378628730774, 0.4266696572303772, 1.8096580505371094, -0.025295833125710487, -0.7902066707611084, 0.40415072441101074, 0.055024653673172, -0.8251221179962158, -1.0524115562438965, -0.9109047055244446, 0.7246547937393188, -0.5449836850166321, -0.8358573317527771, -0.7718902230262756, -2.40669846534729, 0.2778032124042511, -0.2884272038936615, -0.8490129709243774, 1.4675058126449585, 1.1955299377441406, 0.6192570924758911, 0.17508988082408905, -0.0025415420532226562, -1.6332228183746338, 0.13154403865337372, -0.42132869362831116, 1.3339585065841675, -0.9315336346626282, -0.3667951822280884, 0.42352136969566345, 0.850147008895874, 0.5847646594047546, 0.023038294166326523, 0.09768463671207428, -0.747952401638031, 0.012049324810504913, -0.36887988448143005, -0.2136858105659485, -1.4922459125518799, -0.14588728547096252, 0.7344020009040833, -0.6425222754478455, 0.1021447703242302, -1.0822982788085938, -0.957123339176178, 0.2882171869277954, -0.1031985878944397, 0.0638224259018898, 0.26498880982398987, -0.4373978078365326, 1.4665733575820923, -1.1561802625656128, -0.06677502393722534, 0.7316007018089294, 1.2154256105422974, -1.04684579372406, -0.3898836374282837, 0.8378158807754517, -0.15509507060050964, 1.1764930486679077, -0.5040249824523926, 0.4352869987487793, -0.2949807345867157]'

In [19]:
yunet_facenet_predicted = pd.read_csv('../../data/yunet_facenet_predicted.csv', index_col=0)
yunet_facenet_predicted.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath,predicted_name,predicted_tmdb_id
1,6,202,186,436,0,0.781,yunet,8,79,19,...,1080,179.2,234.0,41933,0.020,192,"[0.04235725477337837, -0.42495790123939514, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN
0,365,274,678,608,1,0.723,yunet,91,114,103,...,1080,313.6,334.8,104993,0.051,192,"[0.5490447282791138, -0.17489133775234222, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN
15,717,209,1075,601,0,0.848,yunet,144,102,158,...,1080,358.4,392.4,140636,0.068,216,"[-0.056983813643455505, 0.07135702669620514, -...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN
14,333,191,544,389,1,0.845,yunet,69,74,79,...,1080,211.2,198.0,41818,0.020,216,"[-0.16046729683876038, -0.4248913824558258, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN
13,70,137,230,295,2,0.804,yunet,22,56,29,...,1080,160.0,158.4,25344,0.012,216,"[-0.21441158652305603, -0.8600454330444336, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN

In [21]:
yunet_facenet_predicted[yunet_facenet_predicted['predicted_name'].notna()]

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath,predicted_name,predicted_tmdb_id
5,685,281,1030,605,2,0.820,yunet,119,115,143,...,1080,345.6,324.0,111974,0.054,264,"[-0.8798691034317017, -1.1091086864471436, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
96,563,259,883,554,0,0.839,yunet,106,108,126,...,1080,320.0,295.2,94464,0.046,2064,"[-0.48780104517936707, -0.5013403296470642, 0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
97,589,266,915,619,0,0.892,yunet,106,114,132,...,1080,326.4,352.8,115154,0.056,2088,"[-0.7356278896331787, -1.1302604675292969, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
109,659,187,909,450,0,0.879,yunet,113,78,132,...,1080,249.6,262.8,65595,0.032,2256,"[-0.6651248931884766, -0.26030611991882324, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
108,646,194,877,425,0,0.869,yunet,107,79,123,...,1080,230.4,230.4,53084,0.026,2280,"[-0.20486408472061157, -0.5998502969741821, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2391,1056,148,1280,392,0,0.897,yunet,170,64,188,...,1080,224.0,244.8,54835,0.026,60648,"[-0.3407115638256073, -1.0582715272903442, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
2394,1062,144,1293,385,0,0.901,yunet,172,64,187,...,1080,230.4,241.2,55572,0.027,60672,"[-0.0806458443403244, 0.3190222978591919, -0.6...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
2403,832,248,1325,713,0,0.901,yunet,150,118,178,...,1080,492.8,464.4,228856,0.110,60792,"[-0.3068665564060211, -0.5327250957489014, -1....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
2404,826,281,1312,749,0,0.899,yunet,145,130,170,...,1080,486.4,468.0,227635,0.110,60816,"[-0.6266863346099854, -0.1546480655670166, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
2408,1005,144,1235,346,0,0.915,yunet,167,61,184,...,1080,230.4,201.6,46449,0.022,60864,"[0.8101511001586914, -0.6007542610168457, -0.7...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0

In [22]:
df = pd.read_csv('../../data/yunet_facenet_test_predicted.csv', index_col=0)
df.head()

,x1,y1,x2,y2,face_num,confidence,model,left_eye_x,left_eye_y,right_eye_x,...,img_height,face_width,face_height,area,pct_of_frame,frame_num,encoding,filepath,predicted_name,predicted_tmdb_id
1,6,202,186,436,0,0.781,yunet,8,79,19,...,1080,179.2,234.0,41933,0.020,192,"[0.04235725477337837, -0.42495790123939514, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0
0,365,274,678,608,1,0.723,yunet,91,114,103,...,1080,313.6,334.8,104993,0.051,192,"[0.5490447282791138, -0.17489133775234222, -0....",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,NaN,NaN
15,717,209,1075,601,0,0.848,yunet,144,102,158,...,1080,358.4,392.4,140636,0.068,216,"[-0.056983813643455505, 0.07135702669620514, -...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Omar Epps,4987.0
14,333,191,544,389,1,0.845,yunet,69,74,79,...,1080,211.2,198.0,41818,0.020,216,"[-0.16046729683876038, -0.4248913824558258, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0
13,70,137,230,295,2,0.804,yunet,22,56,29,...,1080,160.0,158.4,25344,0.012,216,"[-0.21441158652305603, -0.8600454330444336, -0...",/home/amos/media/tv/House.MD.2004.S01-08.1080p...,Robert Sean Leonard,2692.0